
Loading components for TIF035

Traceback (most recent call last):
  File "./task2.py", line 61, in <module>
    main()
  File "./task2.py", line 54, in main
    params = opt.leastsq(residual, pInitial, args=(at, forcesDFT))
  File "/beda/sw/apps/scipy/py26/0.7.2/mkl10.2/lib/python2.6/site-packages/scipy/optimize/minpack.py", line 266, in leastsq
Traceback (most recent call last):
  File "./task2.py", line 61, in <module>
    main()
  File "./task2.py", line 54, in main
    params = opt.leastsq(residual, pInitial, args=(at, forcesDFT))
  File "/beda/sw/apps/scipy/py26/0.7.2/mkl10.2/lib/python2.6/site-packages/scipy/optimize/minpack.py", line 266, in leastsq
        m = check_func(func,x0,args,n)[0]
m = check_func(func,x0,args,n)[0]
  File "/beda/sw/apps/scipy/py26/0.7.2/mkl10.2/lib/python2.6/site-packages/scipy/optimize/minpack.py", line 12, in check_func
  File "/beda/sw/apps/scipy/py26/0.7.2/mkl10.2/lib/python2.6/site-packages/scipy/optimize/minpack.py", line 12, in check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],)+args)))
  File "./task2.py", line 17, in residual
    res = atleast_1d(thefunc(*((x0[:numinputs],)+args)))
    latParam = aposat.get_cell()[0][0]/3
  File "./task2.py", line 17, in residual
NameError: global name 'aposat' is not defined
GPAW CLEANUP (node 5): <type 'exceptions.NameError'> occurred.  Calling MPI_Abort!
    latParam = aposat.get_cell()[0][0]/3
NameError: global name 'aposat' is not defined
GPAW CLEANUP (node 1): <type 'exceptions.NameError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./task2.py", line 61, in <module>
    main()
  File "./task2.py", line 54, in main
    params = opt.leastsq(residual, pInitial, args=(at, forcesDFT))
  File "/beda/sw/apps/scipy/py26/0.7.2/mkl10.2/lib/python2.6/site-packages/scipy/optimize/minpack.py", line 266, in leastsq
    m = check_func(func,x0,args,n)[0]
  File "/beda/sw/apps/scipy/py26/0.7.2/mkl10.2/lib/python2.6/site-packages/scipy/optimize/minpack.py", line 12, in check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],)+args)))
  File "./task2.py", line 17, in residual
    latParam = aposat.get_cell()[0][0]/3
NameError: global name 'aposat' is not defined
GPAW CLEANUP (node 0): <type 'exceptions.NameError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./task2.py", line 61, in <module>
    main()
  File "./task2.py", line 54, in main
    params = opt.leastsq(residual, pInitial, args=(at, forcesDFT))
  File "/beda/sw/apps/scipy/py26/0.7.2/mkl10.2/lib/python2.6/site-packages/scipy/optimize/minpack.py", line 266, in leastsq
    m = check_func(func,x0,args,n)[0]
  File "/beda/sw/apps/scipy/py26/0.7.2/mkl10.2/lib/python2.6/site-packages/scipy/optimize/minpack.py", line 12, in check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],)+args)))
  File "./task2.py", line 17, in residual
    latParam = aposat.get_cell()[0][0]/3
NameError: global name 'aposat' is not defined
GPAW CLEANUP (node 2): <type 'exceptions.NameError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./task2.py", line 61, in <module>
    main()
  File "./task2.py", line 54, in main
    params = opt.leastsq(residual, pInitial, args=(at, forcesDFT))
  File "/beda/sw/apps/scipy/py26/0.7.2/mkl10.2/lib/python2.6/site-packages/scipy/optimize/minpack.py", line 266, in leastsq
    m = check_func(func,x0,args,n)[0]
  File "/beda/sw/apps/scipy/py26/0.7.2/mkl10.2/lib/python2.6/site-packages/scipy/optimize/minpack.py", line 12, in check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],)+args)))
  File "./task2.py", line 17, in residual
    latParam = aposat.get_cell()[0][0]/3
NameError: global name 'aposat' is not defined
GPAW CLEANUP (node 7): <type 'exceptions.NameError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./task2.py", line 61, in <module>
    main()
  File "./task2.py", line 54, in main
    params = opt.leastsq(residual, pInitial, args=(at, forcesDFT))
  File "/beda/sw/apps/scipy/py26/0.7.2/mkl10.2/lib/python2.6/site-packages/scipy/optimize/minpack.py", line 266, in leastsq
    m = check_func(func,x0,args,n)[0]
  File "/beda/sw/apps/scipy/py26/0.7.2/mkl10.2/lib/python2.6/site-packages/scipy/optimize/minpack.py", line 12, in check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],)+args)))
  File "./task2.py", line 17, in residual
    latParam = aposat.get_cell()[0][0]/3
NameError: global name 'aposat' is not defined
GPAW CLEANUP (node 4): <type 'exceptions.NameError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./task2.py", line 61, in <module>
    main()
  File "./task2.py", line 54, in main
    params = opt.leastsq(residual, pInitial, args=(at, forcesDFT))
  File "/beda/sw/apps/scipy/py26/0.7.2/mkl10.2/lib/python2.6/site-packages/scipy/optimize/minpack.py", line 266, in leastsq
    m = check_func(func,x0,args,n)[0]
  File "/beda/sw/apps/scipy/py26/0.7.2/mkl10.2/lib/python2.6/site-packages/scipy/optimize/minpack.py", line 12, in check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],)+args)))
  File "./task2.py", line 17, in residual
    latParam = aposat.get_cell()[0][0]/3
NameError: global name 'aposat' is not defined
GPAW CLEANUP (node 6): <type 'exceptions.NameError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./task2.py", line 61, in <module>
    main()
  File "./task2.py", line 54, in main
    params = opt.leastsq(residual, pInitial, args=(at, forcesDFT))
  File "/beda/sw/apps/scipy/py26/0.7.2/mkl10.2/lib/python2.6/site-packages/scipy/optimize/minpack.py", line 266, in leastsq
    m = check_func(func,x0,args,n)[0]
  File "/beda/sw/apps/scipy/py26/0.7.2/mkl10.2/lib/python2.6/site-packages/scipy/optimize/minpack.py", line 12, in check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],)+args)))
  File "./task2.py", line 17, in residual
    latParam = aposat.get_cell()[0][0]/3
NameError: global name 'aposat' is not defined
GPAW CLEANUP (node 3): <type 'exceptions.NameError'> occurred.  Calling MPI_Abort!
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD 
with errorcode 42.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun has exited due to process rank 1 with PID 31642 on
node beda46-3.nfs.private exiting without calling "finalize". This may
have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).
--------------------------------------------------------------------------
[beda46-3.nfs.private:31640] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[beda46-3.nfs.private:31640] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
